-- AquaCore MX - tabla de pedidos para Supabase
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  folio text not null unique,
  mp_order_id text unique,
  payment_id text,
  customer_name text,
  customer_email text,
  customer_phone text,
  address text,
  city text,
  state text,
  zip text,
  reference text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2) not null default 0,
  shipping_amount numeric(12,2) not null default 0,
  shipping_status text not null default 'free',
  payment_status text not null default 'created',
  payment_status_detail text,
  payment_method text,
  currency text not null default 'MXN',
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_payment_status_idx on public.orders (payment_status);
create index if not exists orders_customer_email_idx on public.orders (customer_email);

alter table public.orders enable row level security;

-- No se crean políticas públicas: la tienda accede exclusivamente con
-- SUPABASE_SERVICE_ROLE_KEY desde funciones server-side en Vercel.
